### ISSUE TITLE
Enable gpu acceleration in QWebEngine?

### ISSUE THREAD

**Issue by yxwangcs** [iwalton3/jellyfin-media-player#10]
The web interface feels stuttered due to gpu acceleration being disabled ([this line](https://github.com/iwalton3/jellyfin-media-player/blob/master/src/main.cpp#L84)). After enabling it the interface has the same smoothness as Jellyfin-web. Tested on macOS with QT 5.15.2.

A quick search in the history of Plex Media Player shows that the acceleration was disabled due to crashes and corruption issues. I'm not sure if that's only related to QT 5.9 or not, will update this when I find out more information.

**Comment by iwalton3** [comment]
I think it would be reasonable to enable this and see if anything bad happens.

**Comment by iwalton3** [comment]
This will be in the next release. It tests fine in Windows 10 and Debian Linux.

**Comment by iwalton3** [comment]
> Tested on macOS with QT 5.15.2.

Unrelated but did you happen to get the installer build to work? I would love to make an Azure Pipelines job to build it or something.

**Comment by yxwangcs** [comment]
> > Tested on macOS with QT 5.15.2.
> 
> Unrelated but did you happen to get the installer build to work? I would love to make an Azure Pipelines job to build it or something.

Sort-of, I fixed a few places in the cmake scripts so I can successfully generate the bundle but somehow it does not work properly on another machine. I can create a PR once it works.
