### ISSUE TITLE
Keyboard/Remote navigation

### ISSUE THREAD

**Issue by sPOiDar** [iwalton3/jellyfin-media-player#11]
For TV use, there really needs to be a non-mouse control scheme. Native LIRC support is probably overkill, but being able to navigate via keyboard would allow LIRC and/or bluetooth remote users to navigate the UI. Honestly, even on desktop this would be welcome in some scenarios.

Kodi's default keybinds and navigation paradigms are probably a good point of reference for inspiration.

**Comment by iwalton3** [comment]
If you set TV mode in the settings I believe it supports keyboard navigation. There is some unused code for remote controls that I need to look at using. You can also use the mobile app to control it.

**Comment by sPOiDar** [comment]
I couldn't get keystrokes to do anything useful on the home screen or TV/Movie/etc screens, whether launching with `--tv` or not. Focusing the list container via mouse just makes the arrow keys/whatever control the scrollbar. For clarity, I'm looking for the ability to navigate individual list elements (shows, episodes, etc), as well as access context menus, side navigation, top navigation, etc via keyboard.

Apps are unfortunately a poor substitute for a remote control with a TV.

**Comment by iwalton3** [comment]
`--tv` doesn't do anything. You have to change the option in the web settings right now.

**Comment by sPOiDar** [comment]
I can't find a TV mode setting anywhere, any idea where I should be looking?

**Comment by cm-chandler** [comment]
![image](https://user-images.githubusercontent.com/81978586/114065054-18bfe680-984f-11eb-83bb-4aebcc0b29fd.png)

![image](https://user-images.githubusercontent.com/81978586/114065072-1d849a80-984f-11eb-9d3c-b9847cf14b30.png)

![image](https://user-images.githubusercontent.com/81978586/114065099-25dcd580-984f-11eb-8aba-ce5a2152e924.png)

**Comment by sPOiDar** [comment]
Thank you very much, apologies for my blindness. I presume then that any issues I have with this mode should be reported upstream to `jellyfin-web`?

**Comment by iwalton3** [comment]
Report them to me if they only impact this player or if they are breaking critical functionality I'll fix it and upstream it myself.
