### ISSUE TITLE
4K movie does not work

### ISSUE THREAD

**Issue by gnouts** [iwalton3/jellyfin-media-player#12]
When playing a 4K file the streaming starts, but screen is blue. I only got the sounds and subtitles.

I used the latest flatpak version, under Manjaro.

Jellyfin server : 10.7.1
Transcoding enabled for 4K movie, perfectly working on web player. Though using jellyfin-media-player, transcoding is not triggered (no process runs on my GPU).

**Comment by iwalton3** [comment]
Please send `~/.local/share/jellyfinmediaplayer/logs/jellyfinmediaplayer.log`

**Comment by gnouts** [comment]
[jellyfinmediaplayer.log](https://github.com/iwalton3/jellyfin-media-player/files/6284064/jellyfinmediaplayer.log)

**Comment by iwalton3** [comment]
Are your graphics drivers messed up?

**Comment by gnouts** [comment]
Yes you're right, I did more tests and it's not a jellyfin-media-player issue but my hybrid linux graphics. Thanks and sorry for the noise :)
