### ISSUE TITLE
Media download broken on linux

### ISSUE THREAD

**Issue by gabelluardo** [iwalton3/jellyfin-media-player#14]
I tried v1.2.1 on manjaro with this [aur](https://aur.archlinux.org/packages/jellyfin-media-player) package, and seems it doesn't work

**Comment by iwalton3** [comment]
I'm not surprised. Embedded browsers can handle opening links oddly. I believe there is an API function to open links in a new page.

**Comment by iwalton3** [comment]
This will be fixed in the next release.
