### ISSUE TITLE
Sooo... I have a couple of questions.

### ISSUE THREAD

**Issue by Nocifer** [iwalton3/jellyfin-media-player#16]
1) If I'm not mistaken, just a few weeks ago Jellyfin MPV Shim was officially adopted into the Jellyfin family as Jellyfin Desktop; but now we have a new "Jellyfin Media Player" which also makes use of MPV and is seemingly a newer project but covers the exact same use case? What am I missing here? Is this supposed to be a future replacement for MPV Shim (in desktop mode)? Are the two projects supposed to co-exist? If so, what's the supposed use case for each of them?

2) Is there any way to feed a custom mpv.conf into this app like with MPV Shim, or is the configuration done only via jellyfinmediaplayer.conf?

**Comment by iwalton3** [comment]
This project was an experiment for an alternative desktop client, which proved to have results that exceeded my expectations. It will not replace MPV Shim however if it is successful it may replace the desktop mode in MPV Shim as it is kind of a hack.

You can place an `mpv.conf` into the folder where `jellyfinmediaplayer.conf` resides and it will be used.

**Comment by Nocifer** [comment]
So going forward this could/should become the standalone Jellyfin application for the desktop, while MPV Shim will remain as the tool to be used for streaming stuff via the web UI, and MPV Shim in Desktop-mode will be retired? Nice, then I'll stay with this one, especially since I can use my own mpv.conf. Thanks for the quick reply!

**Comment by iwalton3** [comment]
> especially since I can use my own mpv.conf

MPV Shim also supports that. This player is more intended to provide a "complete" Jellyfin player in a single window. If you want to use and customize the MPV interface and keybindings you are better off with MPV Shim for now.

**Comment by iwalton3** [comment]
Closing as this isn't really an issue.

**Comment by Nocifer** [comment]
> > especially since I can use my own mpv.conf
> 
> MPV Shim also supports that. 

I know, and that's why I like it and use it; but I wanted to know if this app also supports it or not, because otherwise it would be a complete dealbreaker for me and I would stick with MPV Shim.

> This player is more intended to provide a "complete" Jellyfin player in a single window. If you want to use and customize the MPV interface and keybindings you are better off with MPV Shim for now.

Yeah, just figured this out. On the other hand I usually watch stuff on a TV, so for those rare few times I watch on the desktop I'm perfectly fine with having an "official" looking Jellyfin player with its own set of shortcuts - being able to utilize mpv's (configurable) power behind the scenes is what really matters. Not to mention it's also a great solution for setting up Jellyfin access for friends and family who would also benefit from mpv's power, but would probably not appreciate its minimalism :)
