### ISSUE TITLE
Client "hangs" when playing music after a while

### ISSUE THREAD

**Issue by How-Bout-No** [iwalton3/jellyfin-media-player#22]
When I'm streaming music off my server after a while the client kind of "hangs" or "buffers" in between songs for an increasing period of time. It almost seems as if the connection to the server is somehow lost, since I can sort of still navigate but nothing loads (i.e. if I back out to the main screen none of the thumbnails load) and the only way to get it to kick back up is to either wait the unknown time for it to stop buffering (only to have it buffer again when the next song ends) or restart the client. I am unsure if other media is affected like this.
I thought it might be an issue with my server, but streaming songs off the web browser itself never buffers even after a while.

**Comment by iwalton3** [comment]
Oh it was even more spectacular than that. Each time you played a song it would bind another event handler to song endings. And after each time the song ended it would request the metadata from the server once for each event handler.

**Comment by iwalton3** [comment]
Needless to say this will be fixed in the next release.
