### ISSUE TITLE
CSS Themeing inconsistencies

### ISSUE THREAD

**Issue by CTalvio** [iwalton3/jellyfin-media-player#4]
Hello!

I've been testing my CSS themes, and have noticed some things appear to not work quite right. I'll be listing what I find here. Going to investigate as well if I can implement fixes on the theme css code side. These are seen when using the Kaleidochromic theme.

- Background blur does not apply when a page loads, instead plops in about a second later
- Check box check mark is white, should be accent colored
- Icon backgrounds visible (the blue backgrounds around icons in the dashboard, for example), should be removed by theme
- Items in "continue watching" are darkened due to the transparency of the progress bar colors not applying
- Confirmation dialogue boxes (such as when restarting the server) have footer/header colors rendered where they shouldn't be
- Actor list text fields are solid grey

**Comment by iwalton3** [comment]
The latest version now supports devtools so you should be able to better troubleshoot these issues. The client uses QTWebEngine which is based on Chromium. Pass the `--remote-debugging-port=PORT` option and then go to `chrome://inspect/#devices` in a Google Chrome to troubleshoot these issues.

**Comment by CTalvio** [comment]
Just updated, and essentially all issues I mentioned are now gone....

CSS overrides now seem to apply as they should.

**Comment by gggirlgeek** [comment]
So these specific issues are fixed in the next release, or the ability to fix them ourselves with CSS overrides is fixed?
