### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by ilyazzz** [iwalton3/jellyfin-media-player#6]
I've created a flatpak package for this, hugely based on the existing mpv shim flatpak package:
https://github.com/ilyazzz/flathub/tree/com.github.iwalton3.jellyfin-media-player

Currently it points to my fork. Once #5 is merged and you give me the permission to package it, I will submit it to flathub.

**Comment by iwalton3** [comment]
Sorry I'm already one step ahead of you https://github.com/flathub/flathub/pull/2238

**Comment by ilyazzz** [comment]
My bad, I didn't see that.
