### ISSUE TITLE
Jellyfin Media Player should not spam for update

### ISSUE THREAD

**Issue by Ozwel** [iwalton3/jellyfin-media-player#671]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I open the player (several times per day) and I have a full screen message telling me a new version is available.

**Describe the solution you'd like**
I wish I could tick a box "Do not show again" or "Show me again in 1 month".
Or maybe we could have an entry in the settings to check for update every week/month.

**Additional context**
Updating the player makes it incompatible with Jellyfin Server 10.8.x
This is an issue for people upgrading while not owning the server or the server's owner may not wish to upgrade to 10.9 for specific reasons.

**Comment by kofzhanganguo** [comment]
![image](https://github.com/jellyfin/jellyfin-media-player/assets/32073931/7d13bf42-c974-44bc-8813-c5c811d12550)
![image](https://github.com/jellyfin/jellyfin-media-player/assets/32073931/09e19e2c-5298-4d64-9eef-fa2d25792b47)
Just turn off automatic updates in the client settings.
