### ISSUE TITLE
Hardware decoding 

### ISSUE THREAD

**Issue by chmol** [iwalton3/jellyfin-media-player#7]
At a quick glance it works correctly, installed from AUR repro on manjaro. 

But cpu usage is high. If the player rely on mpv it should be able to pass "hwdec=auto".

**Comment by yxwangcs** [comment]
The code is actually capable of hardware decoding, however it is disabled by default for most platforms (see [this](https://github.com/iwalton3/jellyfin-media-player/blob/master/resources/settings/settings_description.json#L260) from e7ebd72246e744b75455a589cbec642e696c7beb). I've never used plex media player so I'm not sure how the settings is configured (perhaps through the web interface of Plex?). Anyway right now you can hack the default settings and recompile to enable hw decoding. Works perfectly for me on macOS with 5700xt at least.

**Comment by iwalton3** [comment]
You can edit your config in:

Windows: `%localappdata%\JellyfinMediaPlayer\jellyfinmediaplayer.conf`
Linux: `~/.local/share/jellyfinmediaplayer/jellyfinmediaplayer.conf`
MacOS: `~/Library/Application Support/Jellyfin Media Player/jellyfinmediaplayer.conf`

It appears I can't push an update to the config after it is installed in a nice way. But I do want to eventually add access to these settings through the web client somehow. The APIs exist there just isn't any UI.

**Comment by chmol** [comment]
That's really cool, editing a config file is good enough for me :)

I changed the line : 

            "hardwareDecoding": "auto",

and restarted the player but I don't see any decrease in CPU usage. 100% compared to 25% with mpv-shim.

**Comment by iwalton3** [comment]
Valid values are enabled and copy. https://github.com/iwalton3/jellyfin-media-player/blob/b9f79f4c57378256de6557bb4be8dafc6741034b/src/player/PlayerComponent.cpp#L1210

**Comment by iwalton3** [comment]
I added a simple settings modal which will be in the next release exposing these settings.
![image](https://user-images.githubusercontent.com/8078788/114292497-d5d35e00-9a5c-11eb-99e3-da80e57f3267.png)
