### ISSUE TITLE
Video player overlay does not appear if next video is started with the "Start Now" option in the "Next episode Playing in x seconds" popup

### ISSUE THREAD

**Issue by cm-chandler** [iwalton3/jellyfin-media-player#8]
JMP version: current 1.2.1
Platform: Windows
Jellyfin Server version: current 10.7.1

If watching a series with a next episode, a popup informing the user "Next episode playing in x seconds" will appear at the end of the current episode. 
![image](https://user-images.githubusercontent.com/81978586/113906475-27dc6100-9789-11eb-88ca-65e61c5e6558.png)

Video player overlay:
![image](https://user-images.githubusercontent.com/81978586/113906810-7f7acc80-9789-11eb-8166-91e5f45c1f6c.png)

If the current episode is still playing AND the next episode is started by pressing the "Start Now" option the next episode will not have a video player overlay. Keyboard shortcuts still work.

However, if you pause the video then start the next episode by pressing the "Start Now" option in the "Next episode Playing in x seconds" popup then the next episode will have the visible video player overlay as expected.

This issue is not seen when accessing the web client through a web browser. However, I have only tried with a 10.7.1 web client.

**Comment by iwalton3** [comment]
I have gotten this to happen exactly once so it seems like a timing thing.

**Comment by iwalton3** [comment]
Can you try replacing the `desktop` folder in `C:\Program Files\Jellyfin\Jellyfin Media Player\web-client` with this one: https://iwalton.com/ushare/desktop_dbg1.zip

I'm having a hard time consistently reproducing this.

**Comment by iwalton3** [comment]
Nevermind when testing hardware acceleration in Windows for the web view it made the race condition consistent. That updated web client I linked will likely fix the issue, and I'll include it in the next release.
